# Generated by Django 4.0.4 on 2022-04-29 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='WOOP', max_length=255, unique=True)),
                ('slug', models.CharField(default='woop', max_length=255, unique=True)),
                ('info', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='WOOP WOOP WOOP', max_length=255, unique=True)),
                ('slug', models.CharField(default='woopwoopwoop', max_length=255, unique=True)),
                ('blurb', models.TextField()),
                ('tags', models.ManyToManyField(to='comic.tag')),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('imgFile', models.FileField(max_length=255, upload_to='')),
                ('notes', models.TextField(blank=True, null=True)),
                ('comic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comic.series')),
                ('tags', models.ManyToManyField(related_name='tags', to='comic.tag')),
            ],
        ),
    ]
