# Generated by Django 4.0.4 on 2022-05-06 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comic', '0002_episode_transcript_alter_series_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='series',
            name='tags',
        ),
    ]
